### ISSUE TITLE
How can I reproduce the rumor detection?

### ISSUE THREAD

**Issue by zcgeqian** [njustkmg/PaddleMM#1]
The image description and image retrieval are common applications for cross-modal, but i don't understand the method of rumor detection using cross-modal. Could you explain it, or which repos i can refer.

**Comment by Ze-Chun** [comment]
u could read this paper Deep Visual-Linguistic Fusion Network Considering Cross-Modal Inconsistency for Rumor Detection

**Comment by zcgeqian** [comment]
> 

Thanks a lot!
